output "region" {
  description = "AWS region"
  value       = var.aws_region
}

output "node_public_ip" {
  description = "The Elastic IP of the Kubernetes Node (Kong Entrypoint)"
  value       = module.k8s_node.node_public_ip
}

output "node_private_ip" {
  description = "The private IP of the Kubernetes Node"
  value       = module.k8s_node.node_private_ip
}

output "ssh_connection_string" {
  description = "SSH command to connect to the node"
  value       = module.k8s_node.ssh_connection_string
}

# ── Generate environment variables file for shell scripts ─────────────────────

resource "local_file" "env_sh" {
  filename = "${path.module}/env.sh"
  content  = <<-EOT
    # Dynamic Environment Variables generated by Terraform
    export NODE_IP="${module.k8s_node.node_public_ip}"
    export PRIVATE_IP="${module.k8s_node.node_private_ip}"
    export AWS_REGION="${var.aws_region}"
    
    # Resolve absolute path to the SSH private key
    INFRA_DIR="$(cd "$(dirname "$${BASH_SOURCE[0]}")/../../.." && pwd)"
    export KEY_PATH="$INFRA_DIR/terraform/environments/agri-catalogue/oas-key.pem"
  EOT
}

# ── Generate hosts.yaml for Kubespray ──────────────────────────────────────────

resource "local_file" "hosts_k8s_yaml" {
  filename = "${path.module}/hosts_k8s.yaml"
  content  = <<-EOT
    all:
      hosts:
        node1:
          ansible_host: ${module.k8s_node.node_public_ip}
          ip: ${module.k8s_node.node_private_ip}
          access_ip: ${module.k8s_node.node_public_ip}
          ansible_user: ubuntu
      children:
        kube_control_plane:
          hosts:
            node1:
        kube_node:
          hosts:
            node1:
        etcd:
          hosts:
            node1:
        k8s_cluster:
          children:
            kube_control_plane:
            kube_node:
        calico_rr:
          hosts: {}
      vars:
        ansible_ssh_common_args: '-o ControlMaster=auto -o ControlPersist=30m -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o StrictHostKeyChecking=no -i /home/rajan/Projects/OAS-Infra/terraform/environments/agri-catalogue/oas-key.pem'
  EOT
}
