output "bastion_public_ip" {
  description = "Bastion Elastic IP — SSH entry + ProxyJump host."
  value       = module.bastion_nat.public_ip
}

output "nginx_public_ip" {
  description = "nginx Elastic IP — the public API base URL (http://<this>/...)."
  value       = module.nginx.public_ip
}

output "node_private_ip" {
  description = "Private IP of the k8s node (Kong NodePort lives here)."
  value       = module.k8s_node.node_private_ip
}

output "db_host_private_ip" {
  value = module.db_host.private_ip
}

# ── Generated helper files (gitignored) ──────────────────────────────────────

resource "local_file" "env_sh" {
  filename        = "${path.module}/env.sh"
  file_permission = "0644"
  content         = <<-EOT
    # Generated by Terraform — source before running scripts.
    export AWS_REGION="${var.aws_region}"
    export BASTION_IP="${module.bastion_nat.public_ip}"
    export NGINX_IP="${module.nginx.public_ip}"
    export NODE_PRIVATE_IP="${module.k8s_node.node_private_ip}"
    export DB_HOST_IP="${module.db_host.private_ip}"
    export KEY_PATH="${abspath(path.module)}/oas-key.pem"
  EOT
}

# Kubespray inventory. Ansible reaches the PRIVATE node through the bastion via
# ProxyCommand. The key is mounted into the Kubespray container at
# /root/.ssh/id_rsa; the same shared key authenticates both bastion and node.
resource "local_file" "hosts_k8s_yaml" {
  filename = "${path.module}/hosts_k8s.yaml"
  content  = <<-EOT
    all:
      hosts:
        node1:
          ansible_host: ${module.k8s_node.node_private_ip}
          ip: ${module.k8s_node.node_private_ip}
          access_ip: ${module.k8s_node.node_private_ip}
          ansible_user: ubuntu
      children:
        kube_control_plane:
          hosts:
            node1:
        kube_node:
          hosts:
            node1:
        etcd:
          hosts:
            node1:
        k8s_cluster:
          children:
            kube_control_plane:
            kube_node:
        calico_rr:
          hosts: {}
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${module.bastion_nat.public_ip}"'
        # Include the node's private IP in the kube-apiserver TLS SANs so kubectl/helm
        # over the bastion tunnel can verify the cert (no insecure-skip-tls-verify).
        supplementary_addresses_in_ssl_keys:
          - ${module.k8s_node.node_private_ip}
  EOT
}
