#!/bin/bash
# Install Kubernetes on the private node via Kubespray (Docker playbook), using
# the inventory generated by terraform. Usage: deploy_kubespray.sh <environment>
set -e

if [ -z "$1" ]; then
  echo "Usage: $0 <environment>"
  exit 1
fi
ENV_NAME="$1"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_DIR="$REPO_ROOT/terraform/environments/$ENV_NAME"

if [ -f "$ENV_DIR/env.sh" ]; then
  source "$ENV_DIR/env.sh"
else
  echo "Error: env.sh not found. Please run 'terraform apply' first in the $ENV_DIR directory." >&2
  exit 1
fi

chmod 600 "$KEY_PATH"

KUBESPRAY_DIR="${KUBESPRAY_DIR:-$REPO_ROOT/../kubespray-upstream}"
KUBESPRAY_ENV="${KUBESPRAY_ENV:-$REPO_ROOT/../kubespray-venv}"

if [ ! -d "$KUBESPRAY_DIR" ]; then
  echo "Cloning Kubespray into $KUBESPRAY_DIR..."
  git clone https://github.com/kubernetes-sigs/kubespray.git "$KUBESPRAY_DIR"
  cd "$KUBESPRAY_DIR"
  git checkout tags/v2.24.1
  cd -
fi

echo "==> Deploying Kubespray..."

if [ -f "$ENV_DIR/hosts_k8s.yaml" ]; then
  mkdir -p "$KUBESPRAY_DIR/inventory/$ENV_NAME"
  cp -f "$ENV_DIR/hosts_k8s.yaml" "$KUBESPRAY_DIR/inventory/$ENV_NAME/hosts.yaml"
else
  echo "Error: hosts_k8s.yaml not found. Please run 'terraform apply' first." >&2
  exit 1
fi

mkdir -p "$KUBESPRAY_DIR/inventory/$ENV_NAME/group_vars/k8s_cluster"
cat <<EOF > "$KUBESPRAY_DIR/inventory/$ENV_NAME/group_vars/k8s_cluster/k8s-cluster.yml"
container_manager: containerd
kube_proxy_mode: iptables
EOF

# Run via Docker to avoid host Python/Ansible version issues.
docker run --rm \
  --mount type=bind,source="${KUBESPRAY_DIR}/inventory",dst=/kubespray/inventory \
  --mount type=bind,source="${KEY_PATH}",dst=/root/.ssh/id_rsa \
  quay.io/kubespray/kubespray:v2.24.1 \
  ansible-playbook -i inventory/$ENV_NAME/hosts.yaml --become --become-user=root -u ubuntu --private-key=/root/.ssh/id_rsa cluster.yml

echo "==> Kubespray deployment complete."
